AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket

Parameters:
  Suffix:
    Type: String
    Description: A unique suffix for your S3 buckets

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - ''
        - - 'pth-speech-'
          - !Ref Suffix
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            Id: myCORSRuleId1

